### ISSUE TITLE
"npm test" fails with Node v10 on Windows 10

### ISSUE THREAD

**Issue by sbonds** [fitnr/sqlite-json#12]
The tests themselves seem fine, but it appears that the test environment keeps a DB open when attempting to remove its underlying file:

Environment:

```
$ node --version
v10.15.3
$ npm --version
6.4.1
```

Test results:

```
$ npm test

> sqlite-json@1.1.0 test C:\Users\testuser\git\sqlite-json
> mocha test.js

  sqliteToJson
    v accepts a filename
    v calls back with all tables in the specified database (94ms)
    v exports a table to JSON
    v saves a table in a database to a file
    v accepts a key option
    v attaches a key to the output
    v filters with a where option
    v filters with a columns option
    v accepts SQL with a callback
    v accepts where, key, columns simultaneously
    v cli works with options (628ms)
    v cli works with SQL (464ms)
    v cli SQL overrides options (470ms)
    1) "after all" hook


  13 passing (2s)
  1 failing

  1) sqliteToJson
       "after all" hook:
     Error: EBUSY: resource busy or locked, unlink 'tmp\foo.db'
      at Object.unlinkSync (fs.js:951:3)
      at rimrafSync (node_modules\rimraf\rimraf.js:306:17)
      at C:\Users\testuser\git\sqlite-json\node_modules\rimraf\rimraf.js:342:5
      at Array.forEach (<anonymous>)
      at rmkidsSync (node_modules\rimraf\rimraf.js:341:26)
      at rmdirSync (node_modules\rimraf\rimraf.js:334:7)
      at rimrafSync (node_modules\rimraf\rimraf.js:304:9)
      at Context.<anonymous> (test.js:211:9)
```

**Comment by fitnr** [comment]
Seems like a Windows problem, not going to lose sleep over it.
